### ISSUE TITLE
`uv` install

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/SWMManywhere#315]
Low priority and can't say I've used `uv` before, but doesn't seem to work for some reason.
```bash
uv init example 
cd example
uv add swmmanywhere
```
Gives error:
```bash
warning: `VIRTUAL_ENV=C:\Users\bdobson\Documents\data\envs\sa` does not match the project environment path `.venv` and will be ignored       
Using CPython 3.11.10
Creating virtual environment at: .venv
Resolved 67 packages in 7.95s
   Built multiurl==0.3.1
   Built julian==0.14
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: llvmlite==0.36.0
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit code: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\bdobson\AppData\Local\uv\cache\builds-v0\.tmpr1A7jY\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdobson\AppData\Local\uv\cache\builds-v0\.tmpr1A7jY\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "C:\Users\bdobson\AppData\Local\uv\cache\builds-v0\.tmpr1A7jY\Lib\site-packages\setuptools\build_meta.py", line 516, in run_setup      
    super().run_setup(setup_script=setup_script)
  File "C:\Users\bdobson\AppData\Local\uv\cache\builds-v0\.tmpr1A7jY\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup      
    exec(code, locals())
  File "<string>", line 55, in <module>
  File "<string>", line 52, in _guard_py_ver
RuntimeError: Cannot install on Python version 3.11.10; only versions >=3.6,<3.10 are supported.
```

**Comment by cheginit** [comment]
I'd recommend using Pixi instead, considering the use of geospatial packages. Pixi uses `uv` under-the-hood. An example can be found [here](https://github.com/cheginit/pywbt/blob/fc9bd31625b9b055ab84f924f3c8dfc754120bcc/pyproject.toml#L259-L324).
